spring:
  application:
    name: spring-13-security
  mongodb:
    uri: ${MONGODB_URI}
    auto-index-creation: true
logging:
  pattern:
    console: "%.-1level[%X{traceId}] %-28logger{0} %-40msg [%thread] %d{HH:mm:ss.SSS}%n"
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF
jwt:
  secret: ${JWT_SECRET}